export type ProjectDetails = {
	id: string;
	year: string;
	status: string;
	category: string;
	title: string;
	lede: string;
	description: string;
	client: string;
	duration: string;
	role: string;
	team: string;
	services: string[];
	technologies: string[];
	liveUrl: string;
	sourceUrl: string;
	headerImage: string;
	darkHeaderImage: string;
	agency: string;
	duty: string;
	industry: string;
	icon: string;
	logo: string;
	logoDark: string;
	cardPreview: string;
};
